name: Release
on:
  push:
    branches:
      - main
      - beta
    pull_request:

jobs:
  release:
    name: Release packages
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Use Node 18"
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: "Install"
      run: npm run phoenix

    - name: "Github Identity"
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git remote set-url origin https://${{github.actor}}:${GH_TOKEN}@github.com/$GITHUB_REPOSITORY

    - name: "Version"
      run: |
        if [ ${{ github.base_ref }} = beta ]; then
          npx lerna version --conventional-prerelease --preid beta --yes --no-private
        else
          npx lerna version --conventional-graduate --yes --no-private
        fi

    - name: "NPM Identity"
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

    - name: "Release"
      run: |
        npx lerna publish from-git --yes